<#
============================================================================
 VELIX - Windows Firewall rule + autostart (Scheduled Task) setup.

 Run this ONCE, as Administrator. Double-clicking it in Explorer runs it as
 your normal user, which will fail the checks below and re-launch itself
 elevated automatically (you'll get one UAC prompt) - or right-click it and
 choose "Run with PowerShell" / "Run as administrator" yourself.

 What this does:
   1. Adds an inbound Windows Firewall rule allowing TCP 3000, scoped to
      the Private and Domain network profiles ONLY (never Public) - so this
      PC is reachable from your own LAN but not from an untrusted network
      such as public Wi-Fi. It does not touch any other firewall rule and
      does not open any other port.
   2. Registers a Scheduled Task ("VELIX Server") that starts the server
      automatically the next time you log into Windows, and can also be
      started/stopped by hand from Task Scheduler at any time.
   3. Does NOT install npm dependencies, does NOT start the server itself
      right now, and does NOT touch DNS, your router, or anything outside
      this PC.

 Safe to re-run: it removes any previous rule/task of the same name first,
 so re-running never creates duplicates.
============================================================================
#>

$ErrorActionPreference = 'Stop'

$ProjectDir   = 'C:\VELIX'
$Port         = 3000
$FirewallName = 'VELIX Web Solutions (port 3000)'
$TaskName     = 'VELIX Server'
$RunnerBat    = Join-Path $ProjectDir 'RUN-VELIX-LOGGED.bat'

# ---------------------------------------------------------------------
# Self-elevate if not already running as Administrator.
# ---------------------------------------------------------------------
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "Re-launching this script as Administrator (you'll see a UAC prompt)..." -ForegroundColor Yellow
    Start-Process powershell.exe -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',"`"$PSCommandPath`"") -Verb RunAs
    exit
}

Write-Host ""
Write-Host "VELIX - installing firewall rule + autostart task" -ForegroundColor Cyan
Write-Host "Project directory: $ProjectDir"
Write-Host ""

if (-not (Test-Path $ProjectDir)) {
    Write-Error "Project directory $ProjectDir was not found. Nothing to install against."
    exit 1
}

# ---------------------------------------------------------------------
# 1. Windows Firewall - inbound TCP $Port, LAN-only profiles.
# ---------------------------------------------------------------------
Write-Host "1. Configuring Windows Firewall..." -ForegroundColor Cyan
Remove-NetFirewallRule -DisplayName $FirewallName -ErrorAction SilentlyContinue

New-NetFirewallRule -DisplayName $FirewallName `
    -Direction Inbound `
    -Action Allow `
    -Protocol TCP `
    -LocalPort $Port `
    -Profile Private,Domain `
    -Program (Get-Command node -ErrorAction SilentlyContinue).Source `
    -Description "Allows inbound connections to the VELIX Node.js server on port $Port, from trusted (Private/Domain) networks only. Does not allow access from Public networks or the internet." `
    | Out-Null

Write-Host "   Rule '$FirewallName' created - TCP $Port allowed on Private/Domain networks only (not Public, not internet)." -ForegroundColor Green
Write-Host ""

# ---------------------------------------------------------------------
# 2. A small wrapper .bat so Task Scheduler's output is captured to a
#    log file (server.js itself is not modified - this just redirects
#    its stdout/stderr when launched this way).
# ---------------------------------------------------------------------
Write-Host "2. Writing the logged startup wrapper..." -ForegroundColor Cyan
$logsDir = Join-Path $ProjectDir 'logs'
if (-not (Test-Path $logsDir)) { New-Item -ItemType Directory -Path $logsDir | Out-Null }

$runnerContent = @"
@echo off
REM Auto-generated by INSTALL-VELIX-SERVICE.ps1 - do not edit by hand.
REM Starts the VELIX server with output appended to logs\server.log.
cd /d "$ProjectDir"
echo. >> logs\server.log
echo ---------------------------------------------- >> logs\server.log
echo %date% %time% - VELIX server starting >> logs\server.log
node server.js >> logs\server.log 2>&1
"@
Set-Content -Path $RunnerBat -Value $runnerContent -Encoding ASCII
Write-Host "   Wrote $RunnerBat (logs to $logsDir\server.log)" -ForegroundColor Green
Write-Host ""

# ---------------------------------------------------------------------
# 3. Scheduled Task - starts the server at logon of the current user.
#    Runs in this user's own session (no stored credentials needed).
#    To instead start before any user logs in, change the trigger to
#    New-ScheduledTaskTrigger -AtStartup and the principal to run as
#    SYSTEM - see README.md for that variant if you need it.
# ---------------------------------------------------------------------
Write-Host "3. Registering the autostart Scheduled Task..." -ForegroundColor Cyan
Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

$action    = New-ScheduledTaskAction -Execute $RunnerBat -WorkingDirectory $ProjectDir
$trigger   = New-ScheduledTaskTrigger -AtLogOn
$settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -ExecutionTimeLimit ([TimeSpan]::Zero) -Hidden
$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Limited

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Description "Starts the VELIX Web Solutions Node.js server (server.js) automatically at logon." | Out-Null

Write-Host "   Task '$TaskName' registered - will start the server the next time $env:USERNAME logs in." -ForegroundColor Green
Write-Host ""

Write-Host "Done." -ForegroundColor Cyan
Write-Host "  - To start the server right now without logging out/in: Start-ScheduledTask -TaskName '$TaskName'"
Write-Host "  - Or just double-click START-VELIX-SERVER.bat in $ProjectDir"
Write-Host "  - To stop it: close the server window, or Stop-ScheduledTask -TaskName '$TaskName' then end the node.exe process"
Write-Host "  - To remove autostart later: Unregister-ScheduledTask -TaskName '$TaskName'"
Write-Host ""
Read-Host "Press Enter to close"
